name: CI-Build

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_USER: root
          DB_HOST: localhost
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Verify with Maven
      env:
        PGPASSWORD: test
        PGUSER: root
      run: |
        echo "Postgres DB is $POSTGRES_DB"
        echo "Postgres User is $PGUSER"
        echo "Postgres PW is $PGPASSWORD"
        psql --dbname=postgres --host localhost --port 5432 --command "SELECT * FROM information_schema.tables"
